#!/usr/bin/env bash
# Generate .env with random credentials for a fresh deployment.
# Run once on setup, then edit .env to set ANTHROPIC_API_KEY and PUBLIC_URL.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"

rand() { openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"; }

cat > "$ROOT/.env" <<EOF
# Generated by scripts/generate-env.sh — do not commit this file.

# --- App ---

ANTHROPIC_API_KEY=
PUBLIC_URL=https://localhost

# --- S3-compatible Object Storage ---

S3_ACCESS_KEY=$(rand 24)
S3_SECRET_KEY=$(rand 48)
S3_BUCKET=deckhand-assets
S3_REGION=us-east-1

# --- OAuth2 ---

OAUTH2_CLIENT_ID=deckhand-editor

# --- Ory Postgres ---

ORY_DB_USER=ory
ORY_DB_PASSWORD=$(rand 32)

# --- Deckhand Postgres ---

DECKHAND_DB_USER=deckhand
DECKHAND_DB_PASSWORD=$(rand 32)
DECKHAND_DB_NAME=deckhand

# --- Ory Secrets ---

KRATOS_COOKIE_SECRET=$(rand 32)
KRATOS_CIPHER_SECRET=$(rand 32)
HYDRA_SYSTEM_SECRET=$(rand 32)
EOF

echo "Generated .env"
echo "Edit it to set ANTHROPIC_API_KEY and PUBLIC_URL, then run: docker compose up -d"
