#!/usr/bin/env bash
# Generate .env and ory/seaweedfs/s3.json with random credentials.
# Usage: ./scripts/generate-env.sh
# Run once on fresh deployment, then edit .env to set ANTHROPIC_API_KEY and PUBLIC_URL.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"

rand() { openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"; }

S3_KEY=$(rand 24)
S3_SECRET=$(rand 48)

cat > "$ROOT/.env" <<EOF
# Generated by scripts/generate-env.sh — do not commit this file.

# --- App ---

ANTHROPIC_API_KEY=
PUBLIC_URL=http://localhost:3008

# --- S3-compatible Object Storage ---

S3_ACCESS_KEY=${S3_KEY}
S3_SECRET_KEY=${S3_SECRET}
S3_BUCKET=deckhand-assets
S3_REGION=us-east-1

# --- OAuth2 ---

OAUTH2_CLIENT_ID=deckhand-editor

# --- Ory Postgres ---

ORY_DB_USER=ory
ORY_DB_PASSWORD=$(rand 32)

# --- Deckhand Postgres ---

DECKHAND_DB_USER=deckhand
DECKHAND_DB_PASSWORD=$(rand 32)
DECKHAND_DB_NAME=deckhand

# --- Ory Secrets ---

KRATOS_COOKIE_SECRET=$(rand 32)
KRATOS_CIPHER_SECRET=$(rand 32)
HYDRA_SYSTEM_SECRET=$(rand 32)
EOF

cat > "$ROOT/ory/seaweedfs/s3.json" <<EOF
{
  "identities": [
    {
      "name": "deckhand",
      "credentials": [
        {
          "accessKey": "${S3_KEY}",
          "secretKey": "${S3_SECRET}"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "Write",
        "List",
        "Tagging",
        "Lock"
      ]
    }
  ]
}
EOF

echo "Generated:"
echo "  .env"
echo "  ory/seaweedfs/s3.json"
echo ""
echo "Edit .env to set ANTHROPIC_API_KEY and PUBLIC_URL, then run: docker compose up -d"
